apiVersion: v1
kind: PersistentVolume
metadata:
  name: prestashop-pv
  labels:
    prestashop_storage: 'true'
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  hostPath:
    path: /data/prestashop
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  labels:
    mariadb_storage: 'true'
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  hostPath:
    path: /data/mariadb
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: 306767-project
  name: prestashop-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: ''
  selector:
    matchLabels:
      prestashop_storage: 'true'

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: 306767-project
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: ''
  selector:
    matchLabels:
      mariadb_storage: 'true'